//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidadv1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CICLO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CICLO()
        {
            this.MATERIA = new HashSet<MATERIA>();
        }
    
        public int id_ciclo { get; set; }
        public int carrera_id { get; set; }
        public string nombre_ciclo { get; set; }
    
        public virtual CARRERA CARRERA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MATERIA> MATERIA { get; set; }
    }
}
