//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidadv1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CONDICIONESTUDIANTEMATERIA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CONDICIONESTUDIANTEMATERIA()
        {
            this.ESTUDIANTEMATERIAEXAMEN = new HashSet<ESTUDIANTEMATERIAEXAMEN>();
        }
    
        public int id_condicion_estudiante_materia { get; set; }
        public string nombre_condicion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ESTUDIANTEMATERIAEXAMEN> ESTUDIANTEMATERIAEXAMEN { get; set; }
    }
}
