//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidadv1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ESTUDIANTEMATERIAEXAMEN
    {
        public int id_estudiante_materia_examen { get; set; }
        public int estudiante_id { get; set; }
        public int materia_id { get; set; }
        public int condicion_estudiante_materia_id { get; set; }
        public string examen1 { get; set; }
        public string recuperatorio_examen1 { get; set; }
        public string examen2 { get; set; }
        public string recuperatorio_examen2 { get; set; }
        public string examen3 { get; set; }
        public string recuperatorio_examen3 { get; set; }
        public string examen_final { get; set; }
        public string examen_integrador { get; set; }
        public string nota_final { get; set; }
    
        public virtual CONDICIONESTUDIANTEMATERIA CONDICIONESTUDIANTEMATERIA { get; set; }
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
