//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaUniversidadv1._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class INSCRIPCIONESTUDIANTEMATERIA
    {
        public int id_inscripcion_estudiante_materia { get; set; }
        public int estudiante_id { get; set; }
        public int materia_id { get; set; }
        public bool estado_inscripcion { get; set; }
        public Nullable<System.DateTime> fecha_inscripcion_estudiante_materia { get; set; }
    
        public virtual ESTUDIANTE ESTUDIANTE { get; set; }
        public virtual MATERIA MATERIA { get; set; }
    }
}
